//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleRules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleRules.RuleResources", typeof(RuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITFOR DELAY statement was found in {0}..
        /// </summary>
        internal static string AvoidWaitForDelay_ProblemDescription {
            get {
                return ResourceManager.GetString("AvoidWaitForDelay_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using WaitFor Delay statements in stored procedures, functions and triggers..
        /// </summary>
        internal static string AvoidWaitForDelay_RuleName {
            get {
                return ResourceManager.GetString("AvoidWaitForDelay_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create ResourceManager for {0} from {1}..
        /// </summary>
        internal static string CannotCreateResourceManager {
            get {
                return ResourceManager.GetString("CannotCreateResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SamplesCategory.
        /// </summary>
        internal static string CategorySamples {
            get {
                return ResourceManager.GetString("CategorySamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE ... without a predicate found in {0}..
        /// </summary>
        internal static string DeleteWithNoPredicateRule_ProblemDescription {
            get {
                return ResourceManager.GetString("DeleteWithNoPredicateRule_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using DELETE ... without a predicate.
        /// </summary>
        internal static string DeleteWithNoPredicateRule_RuleName {
            get {
                return ResourceManager.GetString("DeleteWithNoPredicateRule_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ... INTO ... statement was found in {0}..
        /// </summary>
        internal static string SelectIntoRule_ProblemDescription {
            get {
                return ResourceManager.GetString("SelectIntoRule_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using SELECT ... INTO ... in stored procedures.
        /// </summary>
        internal static string SelectIntoRule_RuleName {
            get {
                return ResourceManager.GetString("SelectIntoRule_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ... LIKE &apos;%value&apos; was found in {0}..
        /// </summary>
        internal static string SelectLikeWildcardRule_ProblemDescription {
            get {
                return ResourceManager.GetString("SelectLikeWildcardRule_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using SELECT ... LIKE &apos;%value&apos; statements, instead consider alternative approaches..
        /// </summary>
        internal static string SelectLikeWildcardRule_RuleName {
            get {
                return ResourceManager.GetString("SelectLikeWildcardRule_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * statement was found in {0}..
        /// </summary>
        internal static string SelectStarRule_ProblemDescription {
            get {
                return ResourceManager.GetString("SelectStarRule_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using SELECT * statements, instead use SELECT [column1], [column2].
        /// </summary>
        internal static string SelectStarRule_RuleName {
            get {
                return ResourceManager.GetString("SelectStarRule_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ... WHERE was found without a NOLOCK statement in {0}..
        /// </summary>
        internal static string SelectWithoutNoLockRule_ProblemDescription {
            get {
                return ResourceManager.GetString("SelectWithoutNoLockRule_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using SELECT ... WHERE without NOLOCK.
        /// </summary>
        internal static string SelectWithoutNoLockRule_RuleName {
            get {
                return ResourceManager.GetString("SelectWithoutNoLockRule_RuleName", resourceCulture);
            }
        }
    }
}
